/**
 * Theme definitions and management.
 * Each theme maps semantic names to CSS custom property values.
 * Persisted to localStorage, applied to :root.
 *
 * Auto-generated by scripts/sync-themes.ts — edit that script, not this file.
 */

export interface Theme {
  label: string;
  bg: string;
  bgSurface: string;
  bgHover: string;
  bgInput: string;
  border: string;
  muted: string;
  text: string;
  subtle: string;
  accent: string;
  green: string;
  yellow: string;
  red: string;
  purple: string;
  cyan: string;
}

export const themes: Record<string, Theme> = {
  "auto-dark": {
    label: "Dark", bg: "#0d1117", bgSurface: "#161b22", bgHover: "#1c2128", bgInput: "#0d1117", border: "#30363d", muted: "#555d68", text: "#e6edf3", subtle: "#8b949e", accent: "#58a6ff", green: "#3fb950", yellow: "#d29922", red: "#f85149", purple: "#bc8cff", cyan: "#56d7c2",
  },
  "auto-light": {
    label: "Light", bg: "#ffffff", bgSurface: "#f6f8fa", bgHover: "#eaeef2", bgInput: "#ffffff", border: "#d0d7de", muted: "#8c959f", text: "#1f2328", subtle: "#656d76", accent: "#0969da", green: "#1a7f37", yellow: "#9a6700", red: "#cf222e", purple: "#8250df", cyan: "#0d7680",
  },
  "dracula": {
    label: "Dracula", bg: "#282a36", bgSurface: "#30323e", bgHover: "#3a3c48", bgInput: "#282a36", border: "#414256", muted: "#707295", text: "#f8f8f2", subtle: "#f8f8f2", accent: "#bd93f9", green: "#50fa7b", yellow: "#f1fa8c", red: "#ff5555", purple: "#ff79c6", cyan: "#8be9fd",
  },
  "catppuccin-mocha": {
    label: "Catppuccin Mocha", bg: "#1e1e2e", bgSurface: "#262636", bgHover: "#303040", bgInput: "#1e1e2e", border: "#55576c", muted: "#6c7086", text: "#cdd6f4", subtle: "#bac2de", accent: "#f5c2e7", green: "#a6e3a1", yellow: "#f9e2af", red: "#f38ba8", purple: "#f5c2e7", cyan: "#94e2d5",
  },
  "catppuccin-macchiato": {
    label: "Catppuccin Macchiato", bg: "#24273a", bgSurface: "#2c2f42", bgHover: "#36394c", bgInput: "#24273a", border: "#585c74", muted: "#6e738d", text: "#cad3f5", subtle: "#b8c0e0", accent: "#f5bde6", green: "#a6da95", yellow: "#eed49f", red: "#ed8796", purple: "#f5bde6", cyan: "#8bd5ca",
  },
  "catppuccin-frappe": {
    label: "Catppuccin Frappe", bg: "#303446", bgSurface: "#383c4e", bgHover: "#424658", bgInput: "#303446", border: "#656c84", muted: "#838ba7", text: "#c6d0f5", subtle: "#b5bfe2", accent: "#f4b8e4", green: "#a6d189", yellow: "#e5c890", red: "#e78284", purple: "#f4b8e4", cyan: "#81c8be",
  },
  "catppuccin-latte": {
    label: "Catppuccin Latte", bg: "#eff1f5", bgSurface: "#eaecf0", bgHover: "#e3e5e9", bgInput: "#eff1f5", border: "#62657d", muted: "#6c6f85", text: "#4c4f69", subtle: "#7c7f93", accent: "#ea76cb", green: "#40a02b", yellow: "#df8e1d", red: "#d20f39", purple: "#ea76cb", cyan: "#179299",
  },
  "nord": {
    label: "Nord", bg: "#2e3440", bgSurface: "#363c48", bgHover: "#404652", bgInput: "#2e3440", border: "#505a6f", muted: "#6f7e9b", text: "#d8dee9", subtle: "#e5e9f0", accent: "#88c0d0", green: "#a3be8c", yellow: "#ebcb8b", red: "#bf616a", purple: "#b48ead", cyan: "#88c0d0",
  },
  "tokyo-night": {
    label: "Tokyo Night", bg: "#1a1b26", bgSurface: "#22232e", bgHover: "#2c2d38", bgInput: "#1a1b26", border: "#3d3f4f", muted: "#787c99", text: "#c0caf5", subtle: "#a9b1d6", accent: "#7aa2f7", green: "#9ece6a", yellow: "#e0af68", red: "#f7768e", purple: "#bb9af7", cyan: "#7dcfff",
  },
  "everforest": {
    label: "Everforest Dark", bg: "#2d353b", bgSurface: "#353d43", bgHover: "#3f474d", bgInput: "#2d353b", border: "#505b59", muted: "#7a8478", text: "#d3c6aa", subtle: "#d3c6aa", accent: "#a7c080", green: "#a7c080", yellow: "#dbbc7f", red: "#e67e80", purple: "#d699b6", cyan: "#83c092",
  },
  "gruvbox": {
    label: "Gruvbox Dark", bg: "#202020", bgSurface: "#282828", bgHover: "#323232", bgInput: "#202020", border: "#48423f", muted: "#746a62", text: "#ddc7a1", subtle: "#ddc7a1", accent: "#d8a657", green: "#a9b665", yellow: "#d8a657", red: "#ea6962", purple: "#d3869b", cyan: "#89b482",
  },
  "ayu-dark": {
    label: "Ayu Dark", bg: "#0f1419", bgSurface: "#171c21", bgHover: "#21262b", bgInput: "#0f1419", border: "#58595d", muted: "#bfbdb6", text: "#bfbdb6", subtle: "#bfbdb6", accent: "#ffb454", green: "#b8cc52", yellow: "#ffb454", red: "#f07178", purple: "#d2a6ff", cyan: "#95e6cb",
  },
  "ayu-mirage": {
    label: "Ayu Mirage", bg: "#242936", bgSurface: "#2c313e", bgHover: "#363b48", bgInput: "#242936", border: "#3c4351", muted: "#707a8c", text: "#cccac2", subtle: "#cccac2", accent: "#ffcc66", green: "#d5ff80", yellow: "#ffcc66", red: "#f28779", purple: "#d4bfff", cyan: "#95e6cb",
  },
  "carbonfox": {
    label: "Carbonfox", bg: "#161616", bgSurface: "#1e1e1e", bgHover: "#282828", bgInput: "#161616", border: "#404040", muted: "#646465", text: "#f2f4f8", subtle: "#dfdfe0", accent: "#be95ff", green: "#25be6a", yellow: "#08bdba", red: "#ee5396", purple: "#be95ff", cyan: "#33b1ff",
  },
  "rose-pine": {
    label: "Rose Pine", bg: "#191724", bgSurface: "#211f2c", bgHover: "#2b2936", bgInput: "#191724", border: "#433f58", muted: "#6e6a86", text: "#e0def4", subtle: "#e0def4", accent: "#c4a7e7", green: "#9ccfd8", yellow: "#f6c177", red: "#eb6f92", purple: "#c4a7e7", cyan: "#9ccfd8",
  },
  "rose-pine-dawn": {
    label: "Rose Pine Dawn", bg: "#faf4ed", bgSurface: "#f5efe8", bgHover: "#eee8e1", bgInput: "#faf4ed", border: "#cbbdcb", muted: "#907aa9", text: "#575279", subtle: "#575279", accent: "#907aa9", green: "#56949f", yellow: "#ea9d34", red: "#b4637a", purple: "#907aa9", cyan: "#56949f",
  },
  "kanagawa": {
    label: "Kanagawa", bg: "#1f1f28", bgSurface: "#272730", bgHover: "#31313a", bgInput: "#1f1f28", border: "#3b3a3b", muted: "#727169", text: "#dcd7ba", subtle: "#c8c093", accent: "#7e9cd8", green: "#76946a", yellow: "#c0a36e", red: "#c34043", purple: "#957fb8", cyan: "#6a9589",
  },
  "onedark": {
    label: "One Dark", bg: "#282c34", bgSurface: "#30343c", bgHover: "#3a3e46", bgInput: "#282c34", border: "#525865", muted: "#717683", text: "#abb2bf", subtle: "#abb2bf", accent: "#61afef", green: "#98c379", yellow: "#e5c07b", red: "#e06c75", purple: "#c678dd", cyan: "#56b6c2",
  },
  "github-dark": {
    label: "GitHub Dark", bg: "#101216", bgSurface: "#181a1e", bgHover: "#222428", bgInput: "#101216", border: "#41464c", muted: "#8b949e", text: "#c9d1d9", subtle: "#c9d1d9", accent: "#58a6ff", green: "#56d364", yellow: "#e3b341", red: "#f78166", purple: "#db61a2", cyan: "#2b7489",
  },
  "gruvbox-light": {
    label: "Gruvbox Light", bg: "#fbf1c7", bgSurface: "#f6ecc2", bgHover: "#efe5bb", bgInput: "#fbf1c7", border: "#d1c5a6", muted: "#928374", text: "#3c3836", subtle: "#7c6f64", accent: "#d79921", green: "#98971a", yellow: "#d79921", red: "#cc241d", purple: "#b16186", cyan: "#689d69",
  },
  "everforest-light": {
    label: "Everforest Light", bg: "#fdf6e3", bgSurface: "#f8f1de", bgHover: "#f1ead7", bgInput: "#fdf6e3", border: "#c3c7b3", muted: "#829181", text: "#5c6a72", subtle: "#5c6a72", accent: "#8da101", green: "#8da101", yellow: "#dfa000", red: "#f85552", purple: "#df69ba", cyan: "#35a77c",
  },
  "tokyo-night-light": {
    label: "Tokyo Night Light", bg: "#d5d6db", bgSurface: "#d0d1d6", bgHover: "#c9cacf", bgInput: "#d5d6db", border: "#3e404a", muted: "#75777f", text: "#343b58", subtle: "#343b58", accent: "#34548a", green: "#485e30", yellow: "#965027", red: "#8c4351", purple: "#5a4a78", cyan: "#166775",
  },
  "palenight": {
    label: "Palenight", bg: "#292d3e", bgSurface: "#313546", bgHover: "#3b3f50", bgInput: "#292d3e", border: "#4f576c", muted: "#8796b0", text: "#959dcb", subtle: "#959dcb", accent: "#c792ea", green: "#c3e88d", yellow: "#ffcb6b", red: "#ff5370", purple: "#c792ea", cyan: "#89ddff",
  },
  "moonfly": {
    label: "Moonfly", bg: "#080808", bgSurface: "#101010", bgHover: "#1a1a1a", bgInput: "#080808", border: "#515254", muted: "#808080", text: "#c6c6c6", subtle: "#c6c6c6", accent: "#80a0ff", green: "#85dc85", yellow: "#e3c78a", red: "#ff5d5d", purple: "#cf87e8", cyan: "#79dac8",
  },
  "nightfox": {
    label: "Nightfox", bg: "#192330", bgSurface: "#212b38", bgHover: "#2b3542", bgInput: "#192330", border: "#4d4f58", muted: "#6c6d77", text: "#cdcecf", subtle: "#dfdfe0", accent: "#63cdcf", green: "#81b29a", yellow: "#dbc074", red: "#c94f6d", purple: "#9d79d6", cyan: "#63cdcf",
  },
  "solarized": {
    label: "Solarized Dark", bg: "#002b36", bgSurface: "#08333e", bgHover: "#123d48", bgInput: "#002b36", border: "#2d525c", muted: "#657b83", text: "#839496", subtle: "#eee8d5", accent: "#268bd2", green: "#859900", yellow: "#b58900", red: "#dc322f", purple: "#d33682", cyan: "#2aa198",
  },
  "flexoki": {
    label: "Flexoki Dark", bg: "#1c1b1a", bgSurface: "#242322", bgHover: "#2e2d2c", bgInput: "#1c1b1a", border: "#3b3a38", muted: "#696864", text: "#cecdc3", subtle: "#cecdc3", accent: "#d0a215", green: "#879a39", yellow: "#d0a215", red: "#d14d41", purple: "#ce5d97", cyan: "#3aa99f",
  },
  "flexoki-light": {
    label: "Flexoki Light", bg: "#fffcf0", bgSurface: "#faf7eb", bgHover: "#f3f0e4", bgInput: "#fffcf0", border: "#2c2b2a", muted: "#575653", text: "#100f0f", subtle: "#909088", accent: "#ad8301", green: "#66800b", yellow: "#ad8301", red: "#af3029", purple: "#a02f6f", cyan: "#24837b",
  },
  "oxocarbon": {
    label: "Oxocarbon Dark", bg: "#161616", bgSurface: "#1e1e1e", bgHover: "#282828", bgInput: "#161616", border: "#3f3f3f", muted: "#646464", text: "#f2f4f8", subtle: "#dde1e6", accent: "#be95ff", green: "#42be65", yellow: "#08bdba", red: "#ee5396", purple: "#be95ff", cyan: "#33b1ff",
  },
  "horizon": {
    label: "Horizon", bg: "#1c1e26", bgSurface: "#24262e", bgHover: "#2e3038", bgInput: "#1c1e26", border: "#41434a", muted: "#6f6f70", text: "#dcdfe4", subtle: "#dcdfe4", accent: "#ee64ac", green: "#29d398", yellow: "#fab795", red: "#e95678", purple: "#ee64ac", cyan: "#59e1e3",
  },
  "vesper": {
    label: "Vesper", bg: "#101010", bgSurface: "#181818", bgHover: "#222222", bgInput: "#101010", border: "#3c3c3c", muted: "#7e7e7e", text: "#ffffff", subtle: "#ffffff", accent: "#ffc799", green: "#99ffe4", yellow: "#ffc799", red: "#ff8080", purple: "#ffc799", cyan: "#99ffe4",
  },
  "poimandres": {
    label: "Poimandres", bg: "#1b1e28", bgSurface: "#232630", bgHover: "#2d303a", bgInput: "#1b1e28", border: "#303a48", muted: "#566c81", text: "#e4f0fb", subtle: "#e4f0fb", accent: "#5de4c7", green: "#5de4c7", yellow: "#fffac2", red: "#d0679d", purple: "#add7ff", cyan: "#5fb3a1",
  },
};

const STORAGE_KEY = "recipe_theme";

export function getStoredTheme(): string {
  return localStorage.getItem(STORAGE_KEY) ?? "auto-dark";
}

export function setStoredTheme(id: string): void {
  localStorage.setItem(STORAGE_KEY, id);
}

export function applyTheme(id: string): void {
  const theme = themes[id];
  if (!theme) return;
  const root = document.documentElement;
  root.style.setProperty("--bg", theme.bg);
  root.style.setProperty("--bg-surface", theme.bgSurface);
  root.style.setProperty("--bg-hover", theme.bgHover);
  root.style.setProperty("--bg-input", theme.bgInput);
  root.style.setProperty("--border", theme.border);
  root.style.setProperty("--muted", theme.muted);
  root.style.setProperty("--text", theme.text);
  root.style.setProperty("--subtle", theme.subtle);
  root.style.setProperty("--accent", theme.accent);
  root.style.setProperty("--green", theme.green);
  root.style.setProperty("--yellow", theme.yellow);
  root.style.setProperty("--red", theme.red);
  root.style.setProperty("--purple", theme.purple);
  root.style.setProperty("--cyan", theme.cyan);
  setStoredTheme(id);
}

export function initTheme(): void {
  applyTheme(getStoredTheme());
}
